import "./globals.css";
import Nav from "./components/Nav";
import { PokemonProvider } from "./hooks/usePokemonApi";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PokemonProvider>
      <Nav/>
      <body>{children}</body>
      </PokemonProvider>
    </html>
  );
}
